//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopClient.GuestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestService.IGuestService")]
    public interface IGuestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/CreateOrUpdate", ReplyAction="http://tempuri.org/IGuestService/CreateOrUpdateResponse")]
        bool CreateOrUpdate(DomainModel.DataContracts.GuestDto guestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/CreateOrUpdate", ReplyAction="http://tempuri.org/IGuestService/CreateOrUpdateResponse")]
        System.Threading.Tasks.Task<bool> CreateOrUpdateAsync(DomainModel.DataContracts.GuestDto guestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/FindGuestById", ReplyAction="http://tempuri.org/IGuestService/FindGuestByIdResponse")]
        DomainModel.DataContracts.GuestDto FindGuestById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestService/FindGuestById", ReplyAction="http://tempuri.org/IGuestService/FindGuestByIdResponse")]
        System.Threading.Tasks.Task<DomainModel.DataContracts.GuestDto> FindGuestByIdAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestServiceChannel : DesktopClient.GuestService.IGuestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestServiceClient : System.ServiceModel.ClientBase<DesktopClient.GuestService.IGuestService>, DesktopClient.GuestService.IGuestService {
        
        public GuestServiceClient() {
        }
        
        public GuestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateOrUpdate(DomainModel.DataContracts.GuestDto guestDto) {
            return base.Channel.CreateOrUpdate(guestDto);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrUpdateAsync(DomainModel.DataContracts.GuestDto guestDto) {
            return base.Channel.CreateOrUpdateAsync(guestDto);
        }
        
        public DomainModel.DataContracts.GuestDto FindGuestById(string id) {
            return base.Channel.FindGuestById(id);
        }
        
        public System.Threading.Tasks.Task<DomainModel.DataContracts.GuestDto> FindGuestByIdAsync(string id) {
            return base.Channel.FindGuestByIdAsync(id);
        }
    }
}
